// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeBook.Api.Persistence;

#nullable disable

namespace TradeBook.Api.Persistence.Migrations
{
    [DbContext(typeof(TradeBookDbContext))]
    partial class TradeBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_subject");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerSubject");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseCurrency = "USD",
                            Code = "EQ-DESK-1",
                            CreatedAtUtc = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Equities Desk 1",
                            OwnerSubject = "0f8fad5b-d9cb-469f-a165-70867728950e"
                        },
                        new
                        {
                            Id = 2,
                            BaseCurrency = "USD",
                            Code = "EQ-DESK-2",
                            CreatedAtUtc = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Equities Desk 2",
                            OwnerSubject = "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                        });
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<byte>("InstrumentType")
                        .HasColumnType("tinyint")
                        .HasColumnName("instrument_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("LotSize")
                        .HasColumnType("int")
                        .HasColumnName("lot_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TickSize")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("tick_size");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "USD",
                            InstrumentType = (byte)1,
                            IsActive = true,
                            LotSize = 1,
                            Name = "Apple Inc.",
                            Symbol = "AAPL",
                            TickSize = 0.01m
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            InstrumentType = (byte)1,
                            IsActive = true,
                            LotSize = 1,
                            Name = "Microsoft Corp.",
                            Symbol = "MSFT",
                            TickSize = 0.01m
                        },
                        new
                        {
                            Id = 3,
                            Currency = "USD",
                            InstrumentType = (byte)1,
                            IsActive = true,
                            LotSize = 1,
                            Name = "Tesla Inc.",
                            Symbol = "TSLA",
                            TickSize = 0.01m
                        },
                        new
                        {
                            Id = 4,
                            Currency = "USD",
                            InstrumentType = (byte)1,
                            IsActive = true,
                            LotSize = 1,
                            Name = "NVIDIA Corp.",
                            Symbol = "NVDA",
                            TickSize = 0.01m
                        });
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.InstrumentPrice", b =>
                {
                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("instrument_id");

                    b.Property<DateTime>("AsOfUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("as_of_utc");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("last_price");

                    b.HasKey("InstrumentId");

                    b.ToTable("instrument_prices", (string)null);

                    b.HasData(
                        new
                        {
                            InstrumentId = 1,
                            AsOfUtc = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPrice = 11.02m
                        },
                        new
                        {
                            InstrumentId = 2,
                            AsOfUtc = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPrice = 8.50m
                        },
                        new
                        {
                            InstrumentId = 3,
                            AsOfUtc = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPrice = 42.10m
                        },
                        new
                        {
                            InstrumentId = 4,
                            AsOfUtc = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPrice = 27.35m
                        });
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<decimal>("AverageCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("average_cost");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("instrument_id");

                    b.Property<long?>("LastTradeId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_trade_id");

                    b.Property<decimal>("NetQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("net_quantity");

                    b.Property<decimal>("RealisedPnl")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("realised_pnl");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("LastTradeId");

                    b.HasIndex("AccountId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("CapturedBySubject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("captured_by_subject");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("external_ref");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<byte>("Side")
                        .HasColumnType("tinyint")
                        .HasColumnName("side");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExecutedAtUtc");

                    b.HasIndex("ExternalRef")
                        .IsUnique()
                        .HasFilter("[external_ref] IS NOT NULL");

                    b.HasIndex("InstrumentId");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.InstrumentPrice", b =>
                {
                    b.HasOne("TradeBook.Api.Persistence.Entities.Instrument", "Instrument")
                        .WithOne()
                        .HasForeignKey("TradeBook.Api.Persistence.Entities.InstrumentPrice", "InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.Position", b =>
                {
                    b.HasOne("TradeBook.Api.Persistence.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeBook.Api.Persistence.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeBook.Api.Persistence.Entities.Trade", "LastTrade")
                        .WithMany()
                        .HasForeignKey("LastTradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Instrument");

                    b.Navigation("LastTrade");
                });

            modelBuilder.Entity("TradeBook.Api.Persistence.Entities.Trade", b =>
                {
                    b.HasOne("TradeBook.Api.Persistence.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeBook.Api.Persistence.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Instrument");
                });
#pragma warning restore 612, 618
        }
    }
}
