using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TradeBook.Api.Persistence.Entities;

namespace TradeBook.Api.Persistence.Configurations;

public sealed class PositionConfiguration : IEntityTypeConfiguration<Position>
{
    public void Configure(EntityTypeBuilder<Position> builder)
    {
        builder.ToTable("positions");
        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id).HasColumnName("id").UseIdentityColumn();
        builder.Property(p => p.AccountId).HasColumnName("account_id");
        builder.Property(p => p.InstrumentId).HasColumnName("instrument_id");
        builder.Property(p => p.NetQuantity).HasColumnName("net_quantity").HasPrecision(18, 4);
        builder.Property(p => p.AverageCost).HasColumnName("average_cost").HasPrecision(18, 6);
        builder.Property(p => p.RealisedPnl).HasColumnName("realised_pnl").HasPrecision(18, 6);
        builder.Property(p => p.LastTradeId).HasColumnName("last_trade_id");
        builder.Property(p => p.UpdatedAtUtc).HasColumnName("updated_at_utc").HasPrecision(3);
        // IsRowVersion() does three things: column type rowversion, value
        // generated by SQL Server on add and update, and concurrency token so
        // EF Core adds it to the WHERE clause of every UPDATE.
        builder.Property(p => p.RowVersion).HasColumnName("row_version").IsRowVersion();

        // One position per account and instrument. This is also the lookup the
        // trade capture handler performs on every execution.
        builder.HasIndex(p => new { p.AccountId, p.InstrumentId }).IsUnique();

        builder.HasOne(p => p.Account).WithMany().HasForeignKey(p => p.AccountId).OnDelete(DeleteBehavior.Restrict);
        builder.HasOne(p => p.Instrument).WithMany().HasForeignKey(p => p.InstrumentId).OnDelete(DeleteBehavior.Restrict);
        builder.HasOne(p => p.LastTrade).WithMany().HasForeignKey(p => p.LastTradeId).OnDelete(DeleteBehavior.Restrict);
    }
}
